name: 'Post Release Comments'
description: 'Identifies issues/pull requests from a Release Changelog and leaves a comment.'
inputs:
  version:
    description: 'Version of the Release'
    required: true
  changelog:
    description: 'Body of the Release Changelog'
    required: true
  gh_token:
    description: comon please work and gimme the gh token
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
