name: 'Post Release Comments'
description: 'Identifies issues/pull requests from a Release Changelog and leaves a comment.'
inputs:
  version:
    description: 'Version of the Release'
    required: true
  changelog:
    description: 'Body of the Release Changelog'
    required: true
  # gh_token:
  #   description: 'GitHub Token: You can probably just do this... gh_token: ${{ secrets.GITHUB_TOKEN }}'
  #   required: true
# outputs:
#   time: # output will be available to future steps
#     description: 'The current time after waiting'
runs:
  using: 'node12'
  main: 'dist/index.js'
