name: 'Post Release Comments'
description: 'Automates the process of commenting on Issues/PRs when related fixes have been released.'
author: 'Duncan McClean'
inputs:
  version:
    description: 'Version of the Release'
    required: true
  changelog:
    description: 'Body of the Release Changelog'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: hash
