name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: v1.0.0
        changelog: 'Brand new feature #8'
        myToken: ${{ secrets.GITHUB_TOKEN }}
